resolver: lts-8.19

packages:
- '.'

extra-deps:
- HsSyck-0.53
- yaml-light-0.1.4
- yaml-light-lens-0.3.3.3
- hnix-0.3.4
- logging-3.0.4

flags: {}

extra-package-dbs: []

nix:
  shell-file: shell.nix
